### ISSUE TITLE
The server seems to need another rebooting

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#636]
Pressing "Run" doesn't seem to do anything. Thanks for your time!

**Comment by suever** [comment]
It seems to be working again. I'll leave this open so I can look back at the logs and figure out what keeps going wrong with it. Thanks for the heads up

**Comment by lmendo** [comment]
It seems to need another reboot. I found it out when testing a new commit (using the commit number as version number in the URL, as you exaplained to me). But I don't think it's related, as I've succesfully done it in the past

**Comment by lmendo** [comment]
I can confirm it wasn't working before I tried that

**Comment by suever** [comment]
Thanks, it's working again. I'll have to dig in a bit to figure out what happened.

**Comment by lmendo** [comment]
Thank you! If you find the problem it would of course be great, but don’t spend too much time. I can just ping you when a reboot is needed

**Comment by lmendo** [comment]
Can you give the server a gentle touch, please? :-)

**Comment by lmendo** [comment]
@suever Sorry to bother you again. I just wanted to make sure you saw my previous comment. The MATL interpreter needs some rebooting

**Comment by suever** [comment]
Sorry I didn't see your last message. I was able to capture some logs from it and restarted it. Should be working now!

```
[2021-06-29 22:21:23,996: INFO/MainProcess] Task matl_online.tasks.matl_task[c6091bb4-5542-45c6-a6d4-7c859ae6f7e9] received
[2021-06-29 22:21:24,008: ERROR/ForkPoolWorker-26] Task matl_online.tasks.matl_task[c6091bb4-5542-45c6-a6d4-7c859ae6f7e9] raised unexpected: EOF("End Of File (EOF). Exception style platform.\n<pexpect.pty_spawn.spawn object at 0x7fb42ce689a0>\ncommand: /octave/bin/octave-cli\nargs: [b'/octave/bin/octave-cli', b'--interactive', b'--quiet', b'--no-init-file', b'--norc', b'--no-history']\nbuffer (last 100 chars): ''\nbefore (last 100 chars): ''\nafter: <class 'pexpect.exceptions.EOF'>\nmatch: None\nmatch_index: None\nexitstatus: None\nflag_eof: True\npid: 643\nchild_fd: 21\nclosed: False\ntimeout: 30\ndelimiter: <class 'pexpect.exceptions.EOF'>\nlogfile: None\nlogfile_read: None\nlogfile_send: None\nmaxread: 2000\nignorecase: False\nsearchwindowsize: None\ndelaybeforesend: None\ndelayafterclose: 0.1\ndelayafterterminate: 0.1\nsearcher: searcher_re:\n    0: re.compile('PEXPECT_PROMPT>')\n    1: re.compile('PEXPECT_PROMPT_')\n    2: re.compile('\\\\A.+?__stdin_prompt>|debug> ')\n    3: re.compile('\\r\\n')")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/matl_online/tasks.py", line 184, in matl_task
    matl(self.octave, *args, folder=self.folder,
  File "/app/matl_online/matl.py", line 201, in matl
    octave.eval("cd('%s');" % escape(folder))
  File "/app/matl_online/octave.py", line 38, in eval
    return self._engine.eval(code, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/octave_kernel/kernel.py", line 247, in eval
    raise e
  File "/usr/local/lib/python3.8/dist-packages/octave_kernel/kernel.py", line 232, in eval
    resp = self.repl.run_command(code.rstrip(),
  File "/usr/local/lib/python3.8/dist-packages/metakernel/replwrap.py", line 242, in run_command
    if self._expect_prompt(timeout=timeout) == 1:
  File "/usr/local/lib/python3.8/dist-packages/metakernel/replwrap.py", line 131, in _expect_prompt
    pos = self.child.expect(expects, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7fb42ce689a0>
command: /octave/bin/octave-cli
args: [b'/octave/bin/octave-cli', b'--interactive', b'--quiet', b'--no-init-file', b'--norc', b'--no-history']
buffer (last 100 chars): ''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 643
child_fd: 21
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: None
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('PEXPECT_PROMPT>')
    1: re.compile('PEXPECT_PROMPT_')
    2: re.compile('\\A.+?__stdin_prompt>|debug> ')
    3: re.compile('\r\n')

```

**Comment by lmendo** [comment]
Thank you so much!!

**Comment by lmendo** [comment]
Thank you! I hope you don't mind me bothering you with this every now and then!

**Comment by lmendo** [comment]
Quick reboot please?

**Comment by suever** [comment]
@lmendo Sorry, meant to respond sooner. I fixed this the other day. And also added a periodic task to restart the server every day so this stops happening until I have more time to look at it!

**Comment by lmendo** [comment]
I think that's a very good solution, thanks!

**Comment by lmendo** [comment]
Hello, Suever! I hope you are doing well. Can you reboot MATL Online? Documentation works, but pressing the "run" button doesn't produce any result

**Comment by lmendo** [comment]
Working now!

**Comment by suever** [comment]
Hey @lmendo, I'm doing well thanks. I am glad it started working. The thing that restarts it nightly must have gotten stuck! Will look into that

**Comment by lmendo** [comment]
Thanks! Don't spend too much time on this, I can let you know if it needs rebooting now and then
